os: linux
language: rust
rust: stable
cache: cargo
env:
  global:
    - NAME=enquirer
    - PKG_CONFIG_ALLOW_CROSS=1
jobs:
  allow_failures:
    - env:
        - SHARD=lint
  fast_finish: true
  include:
    - os: osx
      env:
        - SHARD=test
        - TARGET=x86_64-apple-darwin
    - os: linux
      env:
        - SHARD=test
        - TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env:
        - SHARD=test
        - TARGET=i686-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-5-multilib
            - lib32gcc-5-dev
          update: true
      after_deploy: skip
    - os: linux
      if: tag IS blank
      env:
        - SHARD=lint
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --all --all-targets --all-features -- -D warnings
        - cargo fmt -- --check
    - stage: homebrew
      os: linux
      language: shell
      if: tag IS present
      env:
        - EMAIL=pavan.sss1991@gmail.com
      before_script: skip
      script:
        - cd ..
        - git clone --depth 1 https://pksunkara:$GITHUB_TOKEN@github.com/termapps/homebrew-tap
        - cd homebrew-tap
        - bash update.sh
before_script:
  - rustup target add $TARGET
script:
  - cargo build --target $TARGET
  - cargo test
before_deploy:
  - cargo build --target $TARGET --release
  - export BUILD_NAME=$NAME-$TRAVIS_TAG-$TARGET
  - mkdir $BUILD_NAME
  - cp target/$TARGET/release/$NAME LICENSE *.md $NAME.1 $BUILD_NAME
  - zip $BUILD_NAME.zip -r $BUILD_NAME
deploy:
  edge: true
  provider: releases
  file: ${BUILD_NAME}.zip
  on:
    repo: ${TRAVIS_REPO_SLUG}
    tags: true
    condition: $SHARD = test
